name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyinstaller

    - name: Create README
      run: |
        cat > README.md << 'EOF'
        # WebScanner

        快速扫描 HTTP/HTTPS 端口可用性检测工具。

        ## 使用方法

        ```bash
        ./web_scanner -f ip.txt -t 50 -o 5 -d result
        ```

        ### 参数说明
        - -f, --file: IP列表文件路径 (默认: ip.txt)
        - -t, --threads: 线程数 (默认: 50)
        - -o, --timeout: 超时时间(秒) (默认: 5)
        - -d, --dir: 结果保存目录 (默认: result)

        ## 输出文件
        - http_available_[时间戳].txt: HTTP可用的IP
        - https_available_[时间戳].txt: HTTPS可用的IP
        - all_available_[时间戳].txt: 双协议都可用的IP
        - full_results_[时间戳].json: 完整扫描结果
        EOF

    - name: Build binary
      run: |
        pyinstaller --onefile \
                    --clean \
                    --name web_scanner \
                    web_scanner.py

    - name: Prepare release files
      run: |
        mkdir -p release
        cp dist/web_scanner release/
        cp README.md release/
        cd release
        tar -czf web_scanner_linux_amd64.tar.gz web_scanner README.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/web_scanner_linux_amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
