name: Generate GeoIP Lists
on:
  workflow_dispatch:
    inputs:
      country_code:
        description: '国家/地区代码 (例如: ad, cn, us 等)'
        required: true
        type: string
      
jobs:
  verify-source:
    runs-on: ubuntu-latest
    outputs:
      is_allowed: ${{ steps.check-source.outputs.is_allowed }}
    steps:
      - name: Check request source
        id: check-source
        run: |
          USER_AGENT="${{ github.event.client_payload.client_meta.user_agent }}"
          if [[ "$USER_AGENT" == "CloudflareWorker" ]]; then
            echo "is_allowed=true" >> $GITHUB_OUTPUT
          else
            echo "is_allowed=false" >> $GITHUB_OUTPUT
            echo "::error::此工作流只能由 Cloudflare Worker 触发"
          fi

  check-last-run:
    needs: verify-source
    if: needs.verify-source.outputs.is_allowed == 'true'
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check last run time
        id: check
        run: |
          # 获取最近 24 小时内的运行记录
          LAST_RUN=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/runs" \
            --jq ".workflow_runs[] | select(.conclusion == \"success\" and .inputs.country_code == \"${{ github.event.inputs.country_code }}\") | .created_at" \
            | head -n 1)
          
          if [ -z "$LAST_RUN" ]; then
            echo "No previous successful runs found for this country code"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            # 计算时间差（以秒为单位）
            LAST_RUN_SECONDS=$(date -d "$LAST_RUN" +%s)
            CURRENT_SECONDS=$(date +%s)
            DIFF_HOURS=$(( ($CURRENT_SECONDS - $LAST_RUN_SECONDS) / 3600 ))
            
            if [ $DIFF_HOURS -ge 24 ]; then
              echo "Last run was more than 24 hours ago"
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "Last run was less than 24 hours ago"
              echo "should_run=false" >> $GITHUB_OUTPUT
            fi
          fi

          # 获取所有24小时内运行成功的国家代码
          mkdir -p geoip-info
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/runs" \
            --jq "[.workflow_runs[] | select(.conclusion == \"success\" and (.created_at | fromdateiso8601) >= (now - 86400)) | {country: .inputs.country_code, last_run: .created_at}] | unique_by(.country)" \
            > geoip-info/recent_runs.json
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload status file
        uses: actions/upload-artifact@v4
        with:
          name: status
          path: geoip-info/recent_runs.json

  process-geoip:
    needs: check-last-run
    if: needs.check-last-run.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download and Process GeoIP list
        run: |
          COUNTRY="${{ github.event.inputs.country_code }}"
          
          # 下载文件到临时文件
          wget "https://raw.githubusercontent.com/rdone4425/meta-rules-dat/meta/geo/geoip/${COUNTRY}.list" -O temp.txt
          
          # 分离 IPv4 和 IPv6 地址到单独的文件
          grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}" "temp.txt" > "${COUNTRY}-ipv4.txt"
          grep -E "^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}" "temp.txt" > "${COUNTRY}-ipv6.txt"
          
          # 删除临时文件
          rm temp.txt
        
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: geoip-${{ github.event.inputs.country_code }}
          path: |
            ${{ github.event.inputs.country_code }}-ipv4.txt
            ${{ github.event.inputs.country_code }}-ipv6.txt

  notify-skip:
    needs: check-last-run
    if: needs.check-last-run.outputs.should_run == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Notify too frequent runs
        run: |
          echo "::error::该国家代码在过去24小时内已经运行过。请等待24小时后再试。"
          exit 1
