name: Update IP List

permissions:
  contents: write  # 添加写入权限

on:
  schedule:
    - cron: '30 */4 * * *'  # 每4小时的30分运行，比如 0:30, 4:30, 8:30, 12:30...
  workflow_dispatch:      # 允许手动触发

jobs:
  update-ip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  # 使用 PAT token
          fetch-depth: 0
        
      - name: Download IP list
        run: |
          mkdir -p ip_backup
          curl -o ip_backup/merged_all.txt https://gitlab.com/rdone4425/ip/-/raw/main/ips/merged_all.txt
          
      - name: Remove #cn IPs
        run: |
          # 创建一个不包含 #CN 或 #cn 标记的新文件（不区分大小写）
          grep -v -i "#cn" ip_backup/merged_all.txt > ip_backup/merged_without_cn.txt
          # 替换原文件
          mv ip_backup/merged_without_cn.txt ip_backup/merged_all.txt
          
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # 使用 PAT token
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add ip_backup/
          git commit -m "更新 IP 列表" || echo "没有要提交的更改"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD:${GITHUB_REF_NAME}
