name: Speed Test

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  speedtest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Download IP List
      run: |
        curl -o ip.txt https://raw.githubusercontent.com/rdone4425/yuming-ip/main/ios_rule_script/dns_results_ipv4.txt

    - name: Build and Run Speed Test
      run: |
        go build -o speedtest
        ./speedtest

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test_results.txt

    - name: Update Results to Repository
      run: |
        date "+%Y-%m-%d %H:%M:%S" > last_update.txt
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add test_results.txt last_update.txt
        git commit -m "Update test results" || echo "No changes to commit"
        git push || echo "No changes to push" 
